services:
  api:
    build:
      context: ./api
    container_name: devops-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
    networks:
      - tp-devops-network

  front:
    build:
      context: ./front
    container_name: devops-front
    networks:
      - tp-devops-network

  db:
    build:
      context: ./db
    container_name: devops-db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tp-devops-network

  web:
    build:
      context: ./web
    container_name: devops-web
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - tp-devops-network

networks:
  tp-devops-network:
    driver: bridge

volumes:
  db-data:
