---
# tasks file for roles/launch_proxy
- name: Start Web container
  docker_container:
    name: web
    image: jgazeillescpe/tp-devops-web:latest
    pull: yes
    networks:
      - name: devops-network-proxy
    env_file: "{{ prod_server_app_path }}.env"
    ports:
      - "80:80"
