---
# tasks file for roles/launch_app
- name: Start API container
  docker_container:
    name: api
    image: jgazeillescpe/tp-devops-api:latest
    pull: yes
    networks:
      - name: devops-network-app
      - name: devops-network-proxy
    env_file: "{{ prod_server_app_path }}.env"
