---
# tasks file for roles/lauch_front
- name: Start Front container
  docker_container:
    name: front
    image: jgazeillescpe/tp-devops-front:latest
    pull: yes
    networks:
      - name: devops-network-app
      - name: devops-network-proxy
