---
# tasks file for roles/launch_database
- name: Start Database container
  docker_container:
    name: devops-db
    image: jgazeillescpe/tp-devops-db:latest
    state: started
    restart_policy: always
    networks:
      - name: tp-devops-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
