---
# tasks file for roles/launch_database
- name: Start Database container
  docker_container:
    name: db
    image: jgazeillescpe/tp-devops-db:latest
    pull: yes
    networks:
      - name: devops-network-app
    env_file: "{{ prod_server_app_path }}.env"
    volumes:
      - db-data:/var/lib/postgresql/data
