name: CI Backend Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2.5.0

      - name: Configuration de JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construction et tests avec Maven
        run: mvn clean verify --file ./api/pom.xml
