name: Build and Deploy Docker Containers
on:
  workflow_run:
    workflows: ["SonarQube Analysis"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push front Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push web Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-web:latest
          push: ${{ github.ref == 'refs/heads/main' }}
